apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-auth
  namespace: promtail
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-global
    kind: ClusterSecretStore
  target:
    name: tailscale-auth
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: authkey
      remoteRef:
        key: TAILSCALE_OBSERVABILITY_AUTHKEY
