apiVersion: batch/v1
kind: Job
metadata:
  name: patch-storageclass
  namespace: kube-system
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
      - name: patch
        image: bitnamilegacy/kubectl:1.33.3
        command:
          - /bin/sh
          - -c
          - |
            kubectl patch storageclass local-path \
              -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}' || true
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
      restartPolicy: Never