apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  namespace: argocd
spec:
  destination:
    namespace: istio-ingress
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: gateway
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.24.2
      helm:
        valueFiles:
          - $values/kubernetes/argocd/clusters/addons/software-base/istio-gateway/values.yaml
    - path: kubernetes/argocd/clusters/addons/software-base/istio-gateway
      repoURL: git@github.com:saulbel/stargate-homelab.git
      targetRevision: main
      ref: values
      directory:
        include: "gateway.yaml"
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
