# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: kured
#   namespace: argocd
# spec:
#   destination:
#     namespace: kured
#     server: 'https://kubernetes.default.svc'
#   sources:
#     - chart: kured
#       repoURL: https://kubereboot.github.io/charts
#       targetRevision: 5.11.0
#       helm:
#         valueFiles:
#           - $values/kubernetes/argocd/clusters/addons/software-base/kured/values.yaml
#     - path: kubernetes/argocd/clusters/addons/software-base/kured
#       repoURL: git@github.com:saulbel/stargate-homelab.git
#       targetRevision: main
#       ref: values
#   project: default
#   syncPolicy:
#     syncOptions:
#       - CreateNamespace=true
#     automated:
#       prune: true
#       selfHeal: true