apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  sources:
    - path: kubernetes/argocd/clusters/addons/software-base/nfs
      repoURL: git@github.com:saulbel/stargate-homelab.git
      targetRevision: main
      ref: values
      syncWave: -1   # ExternalSecret first
    - chart: csi-driver-nfs
      repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
      targetRevision: 4.12.0
      syncWave: 0    # NFS CSI Driver second
      helm:
        valueFiles:
          - $values/kubernetes/argocd/clusters/addons/software-base/nfs/values.yaml
        valuesFrom:
          - kind: Secret
            name: nfs-config
            valuesKey: NFS_SERVER
            targetPath: storageClass.parameters.server
          - kind: Secret
            name: nfs-config
            valuesKey: NFS_PATH
            targetPath: storageClass.parameters.share
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
