apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller
  namespace: argocd
spec:
  destination:
    namespace: system-upgrade
    server: 'https://kubernetes.default.svc'
  sources:
    - path: manifests
      repoURL: https://github.com/rancher/system-upgrade-controller.git
      targetRevision: master
    - path: kubernetes/argocd/clusters/addons/software-base/system-upgrade-controller
      repoURL: git@github.com:saulbel/stargate-homelab.git
      targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true