# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: traefik
#   namespace: argocd
# spec:
#   destination:
#     namespace: traefik
#     server: 'https://kubernetes.default.svc'
#   sources:
#     - chart: traefik
#       repoURL: https://traefik.github.io/charts
#       targetRevision: 27.0.0
#       helm:
#         valueFiles:
#           - $values/kubernetes/argocd/clusters/addons/software-base/traefik/values.yaml
#     - path: kubernetes/argocd/clusters/addons/software-base/traefik
#       repoURL: git@github.com:saulbel/stargate-homelab.git
#       targetRevision: main
#       ref: values
#   project: default
#   syncPolicy:
#     syncOptions:
#       - CreateNamespace=true
#     automated:
#       prune: true
#       selfHeal: true