apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd
  namespace: argocd
  annotations:
    external-dns.alpha.kubernetes.io/hostname: argocd.home
    external-dns.alpha.kubernetes.io/target: "192.168.1.200"
spec:
  hosts:
    - argocd.home
  gateways:
    - istio-ingress/homelab-gateway
  http:
    - route:
        - destination:
            host: argocd-server
            port:
              number: 80