apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: tailnet-egress
  namespace: tailscale
spec:
  type: egress
  hostname: "k8s-egress"
  socks5Proxy:
    enabled: true
  replicas: 1