apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: longhorn
  namespace: longhorn
  annotations:
    external-dns.alpha.kubernetes.io/hostname: longhorn.home
    external-dns.alpha.kubernetes.io/target: "192.168.1.200"
spec:
  hosts:
    - longhorn.home
  gateways:
    - istio-ingress/homelab-gateway
  http:
    - route:
        - destination:
            host: longhorn-frontend
            port:
              number: 80
