# Kiali server configuration
istio_namespace: istio-system

auth:
  strategy: anonymous

deployment:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi
  ingress:
    enabled: false

server:
  web_fqdn: kiali.home
  web_root: /

external_services:
  istio:
    root_namespace: istio-system
    ingress_gateway_namespace: istio-ingress
    egress_gateway_namespace: ""
    component_status:
      enabled: true
      components:
        - app_label: ingressgateway
          is_core: true
          namespace: istio-ingress
      # No egress gateway deployed
  prometheus:
    url: http://ubuntu-arm.tail991cf.ts.net:9090
  tracing:
    enabled: false
  grafana:
    enabled: false
