# Kiali server configuration
istio_namespace: istio-system

auth:
  strategy: anonymous

deployment:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi
  ingress:
    enabled: false

server:
  web_fqdn: kiali.home
  web_root: /

external_services:
  istio:
    root_namespace: istio-system
    ingress_gateway_namespace: istio-ingress
    egress_gateway_namespace: ""
    component_status:
      enabled: false
  prometheus:
    url: http://ubuntu-arm.tail991cf.ts.net:9090
  tracing:
    enabled: false
  grafana:
    enabled: false

kiali_feature_flags:
  validations:
    ignore:
      - "KIA0501" # ignote missing sidecar working
      - "KIA0301" # ignore missing authorization policy
      - "KIA0201" # ignore missing app/version label
