apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kiali
  namespace: istio-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kiali.home
spec:
  hosts:
    - kiali.home
  gateways:
    - istio-ingress/homelab-gateway
  http:
    - route:
        - destination:
            host: kiali
            port:
              number: 20001
