# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: nfs-config
#   namespace: kube-system
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: infisical-global
#     kind: ClusterSecretStore
#   target:
#     name: nfs-config
#   data:
#     - secretKey: NFS_SERVER
#       remoteRef:
#         key: NFS_SERVER_IP
#     - secretKey: NFS_PATH
#       remoteRef:
#         key: NFS_EXPORT_PATH