storageClass:
  create: true
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  parameters:
    server:
      valueFrom:
        secretKeyRef:
          name: nfs-config
          namespace: kube-system
          key: NFS_SERVER
    share:
      valueFrom:
        secretKeyRef:
          name: nfs-config
          namespace: kube-system
          key: NFS_PATH
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  mountOptions:
    - nfsvers=4.1