apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - rbac-default-sa.yaml
  - system-upgrade-controller.yaml
  - manual-patching-plan.yaml
  - manual-upgrading-plan.yaml
