apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference Rancher's official manifests as base
bases:
  - github.com/rancher/system-upgrade-controller/manifests?ref=v0.18.0

# Add your custom resources (Plans, etc)
resources:
  - manual-patching-plan.yaml
  - manual-upgrading-plan.yaml

# Target namespace
namespace: system-upgrade